# Workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Trigger on push to main branch
  push:
    branches: ['main']

  # Manual workflow trigger
  workflow_dispatch:

# GitHub token permissions for Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent concurrent deployments
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job to generate static files
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: './dist'

  # Deploy job to publish to GitHub Pages
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
